### ISSUE TITLE
Add support for Adobe Photoshop Elements 10 - 14

### ISSUE THREAD

**Issue by syneryder** [filtermeister/innosetup#3]
The current Photoshop Elements detection code is artificially capped at version 9 and earlier.  Adobe is now up to version 14.  It might be a trivial fix that only requires changing one number and doing some testing.

One catch: the current Elements detection code only supports 32-bit plugins, and presumably Elements now supports 64-bit plugins.

**Comment by vanderlee** [comment]
There are trial downloads available for Elements14, which may contain the plug-in path information.

**Comment by vanderlee** [comment]
I've got Elements14/64 detected (trials can be downloaded here: https://helpx.adobe.com/nl/photoshop-elements/kb/photoshop-elements-downloads.html), but it's slightly different from Elements9/32 to the point where I wonder if Elements9/32 is detected correctly with the current code at all. Can you actually test and confirm the Elements9 code? I can't find any Elements version prior to 10, and starting with 10, it's slightly different.
