### ISSUE TITLE
Add code signing support

### ISSUE THREAD

**Issue by syneryder** [filtermeister/innosetup#4]
With Microsoft deprecating support for SHA-1 code signed files as of 2016 in Windows 10, there's a need to support signing installers with SHA-256 certificates (and also SHA-1 for backwards compatibility).  Microsoft Edge has started flagging files that aren't SHA-256 signed, and in some cases Windows 10 is refusing to run files at all.

The code-signing should be baked into the script as/if necessary, so that building the installer can be a one-step process.

Kohan is a fan of using kSign to sign installers, as it doesn't require downloading the entire Windows SDK just to get a code-signing tool.  Eventually support could be added for signcode.exe, signtool.exe and other tools, and allowing the filter developer to choose between them.

http://codesigning.ksoftware.net/#ksign (click on _Download kSign (New!)_)

The default should be _not_ to sign files, as most developers don't do this and it costs extra money to do so.  We want to make it easy for plug-in creators to get started & bootstrap themselves and to support all the free plugin developers too.

**Comment by vanderlee** [comment]
Do you know how to create a self-signed Authenticode certificate without having to install 2GB of Windows SDK? A self-signed cert would be good enough for testing the script code.

**Comment by vanderlee** [comment]
Found this tool: https://www.pluralsight.com/blog/software-development/selfcert-create-a-self-signed-certificate-interactively-gui-or-programmatically-in-net

Just pushed an example which uses kSign and a self-signed certificate for testing.

Please double-check it.

**Comment by syneryder** [comment]
Awesome, I'll try to test the code soon.  I've also got some code finished here that works with Microsoft's own signtool.exe, so I'll give both a test & push some updated code.

**Comment by syneryder** [comment]
Tested the code, looks awesome, thank you. Added some extra code to support Microsoft's signing tool as well.  Looks like we can tick this one off the list.

**Comment by vanderlee** [comment]
Nice work on the signtool and the preprocessor usage.

I noticed you had two signtool statements; a sha256 and a sha1; does this wrap two layers or something? I thought sha1 signing was deprecated.

**Comment by syneryder** [comment]
Yep, it signs it with both - SHA1 is deprecated and not supported on Windows 10, but it's required for anyone still running a Windows XP machine (which doesn't support SHA256).  Unfortunately kSign doesn't support dual signing just yet. Hopefully not too many XP users left, but I know I've got at least a few still around.
