### ISSUE TITLE
Refactor .iss file into separate files

### ISSUE THREAD

**Issue by vanderlee** [filtermeister/innosetup#5]
Splitting the .iss sourccode into multiple, separate files could make it easier to "pick and choose" different workflows and feature sets.

**Comment by vanderlee** [comment]
Split out detection- and locale-specific code.

**Comment by syneryder** [comment]
I think we're mostly done splitting this out now?  (Though we could maybe break out the language specific "Plug-in" spellings into a separate file in /common, or merging it into common/locale.iss if possible.)

It does seem we can delete simple-installer-3264.iss now, the functionality is all included in install-custom-folder.iss.  There's maybe room to create a new install-simple.iss that is really, really stripped down for newbies (ie folks who just want to wrap their 8BF file in an installer), but either way I think "simple-installer-3264.iss" can be deleted now.  At the very least, that filename I came up with is terribly awkward & confusing!

**Comment by vanderlee** [comment]
I'm all done splitting up myself. There's probably some smart refactoring left to be done (ideally none of the `[code]` should be in the "config" files, perhaps a `common\ui.iss`?), but the big chunks are out.

I agree with the idea of having multiple types of files to support multiple scenario's, and I think we could probably make this happen without too much code duplication by using the preprocessor.

For now it seems the original `simple-installer-3264.iss` can be replaced with the new script. I don't particularly like the `install-custom-folder.iss` name either. Do you have any ideas for a name? Keeping in mind multiple scripts, perhaps something like " install.iss"?

**Comment by vanderlee** [comment]
Done the rename to `install.iss`. Also updated the readme file
